POST http://localhost:8080/rental_web_app/api/house/create
Content-Type: application/json

{
  "address": "Havnegade 1",
  "city": "København",
  "numberOfRooms": "5"
}

###

GET http://localhost:8080/rental_web_app/api/house/all

###

POST http://localhost:8080/rental_web_app/api/rental/create
Content-Type: application/json

{
  "startDate": {
    "year": 2023,
    "month": 7,
    "day": 1
  },
  "endDate": {
    "year": 2023,
    "month": 7,
    "day": 8
  },
  "priceAnnual": 1000,
  "deposit": 20,
  "contactPerson": "Oda",
  "house": 1
}

###

GET http://localhost:8080/rental_web_app/api/rental/all

###

POST http://localhost:8080/rental_web_app/api/rental/assign/user/1
Content-Type: application/json

###

POST http://localhost:8080/rental_web_app/api/rental/remove/user/1
Content-Type: application/json

###

PUT http://localhost:8080/rental_web_app/api/rental/update
Content-Type: application/json

{
  "id": 3,
  "startDate": {
    "year": 2024,
    "month": 7,
    "day": 1
  },
  "endDate": {
    "year": 2024,
    "month": 7,
    "day": 8
  },
  "priceAnnual": 1000,
  "deposit": 20,
  "contactPerson": "Bastian",
  "house": 1
}

###

DELETE http://localhost:8080/rental_web_app/api/rental/delete/2
Content-Type: application/json

###

POST http://localhost:8080/rental_web_app/api/rental/create
Content-Type: application/json

{
  "startDate": "2023-07-01",
  "endDate": "2023-07-08",
  "priceAnnual": 1000,
  "deposit": 20,
  "contactPerson": "Morten",
  "house": 1
}

###

GET http://localhost:8080/rental_web_app/api/user/all

###

PUT http://localhost:8080/rental_web_app/api/rental/update
Content-Type: application/json

{
  "id": 3,
  "startDate": "2024-07-01",
  "endDate": "2024-07-08",
  "priceAnnual": 1000,
  "deposit": 20,
  "contactPerson": "Bastian",
  "house": 1
}

###







